name: Build whitepaper

on: [pull_request]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::$(printf '"%s" ' whitepaper/Innholdsfortegnelse.md)"

      - uses: docker://pandoc/latex:2.9
        with:
          args: --filter pandoc-include --output=build/whitepaper.pdf ${{ steps.files_list.outputs.files }} 
          
      - uses: actions/upload-artifact@master
        with:
          name: whitepaper
          path: build/whitepaper.pdf